language: node_js
node_js:
  - "14"

cache: npm

script: 
  - npm test

jobs:
  include:
    - stage: npm release
      node_js: 14
      script:
        - npm install
        - npm run build
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          branch: master
      